services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ggmsgr
    depends_on:
      - centrifugo


  centrifugo:
    image: centrifugo/centrifugo:latest
    command: centrifugo -c /centrifugo/config.json
    volumes:
      - ./configs/centrifugo.json:/centrifugo/config.json
    ports:
      - "8010:8010"
    networks:
      - ggmsgr


networks:
  ggmsgr:
    driver: bridge
