version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"


  centrifugo:
    image: centrifugo/centrifugo:latest
    command: centrifugo -c /centrifugo/config.json
    volumes:
      - ./configs/centrifugo.json:/centrifugo/config.json
    ports:
      - "8010:8010"


volumes:
  postgres_data:
